=== AppRapport/LickiLicky/Codes from seniors/EI Final Submission/Documentation and Executable/b. Code, Scripts, Exported TIBCO Project/Project/xsd/CarparkList.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="CarparkList">
    <xs:complexType>
      <xs:sequence>
        <xs:element maxOccurs="unbounded" ref="carpark"/>
        <xs:element ref="validfrom"/>
        <xs:element ref="validtill"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="carpark">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="carpark_id"/>
        <xs:element ref="company"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="carpark_id" type="xs:string"/>
  <xs:element name="company" type="xs:string"/>
  <xs:element name="validfrom" type="xs:string"/>
  <xs:element name="validtill" type="xs:string"/>
</xs:schema>

=== AppRapport/LickiLicky/Codes from seniors/EI Final Submission/Documentation and Executable/b. Code, Scripts, Exported TIBCO Project/Project/data/CarparkList.xml
<?xml version = "1.0" encoding = "UTF-8"?>
<CarparkList xmlns:xsi = "http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation = "C:/EI/Project/xsd/CarparkList.xsd">  
	<carpark>   
		<carpark_id>BIBE36</carpark_id>  
		<company>hdb</company>  
	</carpark>
	<carpark>   
		<carpark_id>BIBE37</carpark_id>  
		<company>hdb</company>  
	</carpark>
	<carpark>   
		<carpark_id>BIBE38</carpark_id> 
		<company>hdb</company>  
	</carpark>
	<carpark>   
		<carpark_id>U001</carpark_id>  
		<company>ura</company>  
	</carpark>
	<carpark>   
		<carpark_id>U002</carpark_id>  
		<company>ura</company>  
	</carpark>
	<carpark>   
		<carpark_id>U003</carpark_id> 
		<company>ura</company>  
	</carpark>
	<validfrom>2012-04-02 00:00:00</validfrom>
	<validtill>2012-04-02 23:59:59</validtill>
</CarparkList>
