=== AppRapport/LickiLicky/Codes from seniors/EI Final Submission/Documentation and Executable/b. Code, Scripts, Exported TIBCO Project/Project/xsd/summon.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
  <xs:element name="summon">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="sid"/>
        <xs:element ref="vehno"/>
        <xs:element ref="carparkid"/>
        <xs:element ref="time"/>
        <xs:element ref="seasonpark"/>
        <xs:element ref="fineapplicable"/>
        <xs:element ref="offence"/>
        <xs:element ref="fineamt"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="sid" type="xs:string"/>
  <xs:element name="vehno" type="xs:string"/>
  <xs:element name="carparkid" type="xs:string"/>
  <xs:element name="time" type="xs:string"/>
  <xs:element name="seasonpark" type="xs:string"/>
  <xs:element name="fineapplicable" type="xs:string"/>
  <xs:element name="offence" type="xs:string"/>
  <xs:element name="fineamt" type="xs:string"/>
</xs:schema>

=== AppRapport/LickiLicky/Codes from seniors/EI Final Submission/Documentation and Executable/b. Code, Scripts, Exported TIBCO Project/summon.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?><summon xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="summon.xsd">
	<sid>bf69ec6f-8c86-4aec-abd4-508c288d93f9</sid>
	<vehno>SKK1100H</vehno>
	<carparkid>BIBE37</carparkid>
	<time>2012/04/03 14:22:25</time>
	<seasonpark/>
	<fineapplicable>N.A.</fineapplicable>
	<offence>18(1)</offence>
	<fineamt>NIL</fineamt>        
</summon>
